name: generate snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch: {}
  push:
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: generate snake svg
        uses: Platane/snk@v3
        with:
          github_user_name: SathvikaSingoti
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%2358a6ff&color_dots=%230d1117,%2321262d,%23234c6e,%232f6feb,%2358a6ff

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
